### ISSUE TITLE
Improve test guards for downlevel OpenSSL versions

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/oqs-provider#144]
> Despite this passing CI tests on the branch, it has failed when merged to main: https://github.com/open-quantum-safe/oqs-provider/actions/runs/4809818002/jobs/8561583885
> 
> Anyone have any ideas why?

It seems github CI does not run on PRs (but on main) Needs investigation.

The failing test is a CA test that _should_ only run on OpenSSL Master (as it fails expectedly on 3.0 which is tested in github CI). Probably needs an additional execution guard. If none of you has time for this, I'll Look into this when I am back.

_Originally posted by @baentsch in https://github.com/open-quantum-safe/oqs-provider/issues/143#issuecomment-1523873593_

**Comment by bhess** [comment]
The tests pass up to `sphincssha256128frobust`, CMS tests seem to skip as expected because of 3.0.
I re-run an earlier (previously passing using OpenSSL 3.0) CI run which now also fails, which might point to an issue with an "external" change (liboqs, openssl or docker test-image), see also Alex's analysis https://github.com/open-quantum-safe/oqs-provider/pull/143#issuecomment-1524027127.
The failing sphincsplus test could also point to large signature issues as in https://github.com/open-quantum-safe/oqs-provider/issues/121.

**Comment by bhess** [comment]
The error happens in liboqs sha2_ossl.c. Potentially a regression of https://github.com/open-quantum-safe/liboqs/pull/1431.

```
(gdb) bt
#0  __GI__exit (status=status@entry=1) at ../sysdeps/unix/sysv/linux/_exit.c:30
#1  0x00007ffff7645552 in __run_exit_handlers (status=1, listp=<optimized out>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true)
    at ./stdlib/exit.c:136
#2  0x00007ffff7645610 in __GI_exit (status=<optimized out>) at ./stdlib/exit.c:143
#3  0x00007ffff6bb5c5e in OQS_SHA2_sha256_inc_init (state=0x7fffffffd320) at /data/bhe/git/oqs-provider/liboqs/src/common/sha2/sha2_ossl.c:51
#4  0x00007ffff70121e3 in PQCLEAN_SPHINCSSHA256128FROBUST_AVX2_seed_state (hash_state_seeded=0x7fffffffd320, 
    pub_seed=0x55555567b780 "AA\005\062\250\270.W\222bܚ\ag\273\017")
    at /data/bhe/git/oqs-provider/liboqs/src/sig/sphincs/pqclean_sphincs-sha256-128f-robust_avx2/sha256.c:69
#5  0x00007ffff701170f in PQCLEAN_SPHINCSSHA256128FROBUST_AVX2_initialize_hash_function (hash_state_seeded=0x7fffffffd320, 
    pub_seed=0x55555567b780 "AA\005\062\250\270.W\222bܚ\ag\273\017", 
    sk_seed=0x555555666180 "\ab˨\214w\322W-\330\327\344\347y\032m\237l\313\n\201\233B\364\177\206\267\257\247")
    at /data/bhe/git/oqs-provider/liboqs/src/sig/sphincs/pqclean_sphincs-sha256-128f-robust_avx2/hash_sha256.c:19
#6  0x00007ffff6b51c83 in PQCLEAN_SPHINCSSHA256128FROBUST_AVX2_crypto_sign_seed_keypair (pk=0x55555567b780 "AA\005\062\250\270.W\222bܚ\ag\273\017", 
    sk=0x555555666180 "\ab˨\214w\322W-\330\327\344\347y\032m\237l\313\n\201\233B\364\177\206\267\257\247", 
    seed=0x7fffffffd6f0 "\ab˨\214w\322W-\330\327\344\347y\032m\237l\313\n\201\233B\364\177\206\267\257\247")
    at /data/bhe/git/oqs-provider/liboqs/src/sig/sphincs/pqclean_sphincs-sha256-128f-robust_avx2/sign.c:100
#7  0x00007ffff6b51d79 in PQCLEAN_SPHINCSSHA256128FROBUST_AVX2_crypto_sign_keypair (pk=0x55555567b780 "AA\005\062\250\270.W\222bܚ\ag\273\017", 
    sk=0x555555666180 "\ab˨\214w\322W-\330\327\344\347y\032m\237l\313\n\201\233B\364\177\206\267\257\247")
    at /data/bhe/git/oqs-provider/liboqs/src/sig/sphincs/pqclean_sphincs-sha256-128f-robust_avx2/sign.c:122
#8  0x00007ffff6b4fcaf in OQS_SIG_sphincs_sha256_128f_robust_keypair (public_key=0x55555567b780 "AA\005\062\250\270.W\222bܚ\ag\273\017", 
    secret_key=0x555555666180 "\ab˨\214w\322W-\330\327\344\347y\032m\237l\313\n\201\233B\364\177\206\267\257\247")
    at /data/bhe/git/oqs-provider/liboqs/src/sig/sphincs/sig_sphincs_sha256_128f_robust.c:47
#9  0x00007ffff6a79f79 in OQS_SIG_keypair (sig=0x555555672990, public_key=0x55555567b780 "AA\005\062\250\270.W\222bܚ\ag\273\017", 
    secret_key=0x555555666180 "\ab˨\214w\322W-\330\327\344\347y\032m\237l\313\n\201\233B\364\177\206\267\257\247")
    at /data/bhe/git/oqs-provider/liboqs/src/sig/sig.c:629
#10 0x00007ffff6a4cfa9 in oqsx_key_gen_oqs (key=0x5555556631f0, gen_kem=0) at /data/bhe/git/oqs-provider/oqsprov/oqsprov_keys.c:832
#11 0x00007ffff6a4d5c4 in oqsx_key_gen (key=0x5555556631f0) at /data/bhe/git/oqs-provider/oqsprov/oqsprov_keys.c:934
#12 0x00007ffff6a4e853 in oqsx_genkey (gctx=0x5555556da890) at /data/bhe/git/oqs-provider/oqsprov/oqs_kmgmt.c:456
#13 0x00007ffff6a4e8ef in oqsx_gen (genctx=0x5555556da890, osslcb=0x7ffff7c04750 <ossl_callback_to_pkey_gencb>, cbarg=0x5555556da7d0)
    at /data/bhe/git/oqs-provider/oqsprov/oqs_kmgmt.c:469
#14 0x00007ffff7bf8510 in evp_keymgmt_util_gen () from /data/bhe/git/oqs-provider/.local/lib64/libcrypto.so.3
#15 0x00007ffff7c04bf3 in EVP_PKEY_generate () from /data/bhe/git/oqs-provider/.local/lib64/libcrypto.so.3
#16 0x00005555555fb1cd in app_keygen ()
#17 0x00005555555ccb64 in req_main ()
#18 0x00005555555c1002 in do_cmd ()
#19 0x000055555559c59f in main ()
(gdb) 
```
